### ISSUE TITLE
Question about ConfigureAwait(false)

### ISSUE THREAD

**Issue by neven10** [tdtorre/MyFridge#1]
Really sorry for opening this up, but i can't find proper answer on the internet for this and it's bugging me.

You are using ConfigureAwait(false) in a component so it doesn't wait for sync context in state.
Is there a particular reason for this? 
Why not just await Task in a component method?

**Comment by tdtorre** [comment]
Hi @neven10 thanks for your feedback. First of all, that code was just a demo project for a demo and it could be improved a lot. 

Regarding your proposal, yes we could make that method **async** and use **await** for this call but the ConfigureAwait has some benefits and I used to use it. Take a look at [this](https://johnthiriet.com/configure-await/).
